server:
  registerDefaultExceptionMappers: false
  rootPath: /v1/*
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1 # only bind to loopback
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1 # only bind to loopback

swagger:
  resourcePackage: io.minebox.resource

# Logging settings.
logging:
  level: INFO
  loggers:
    io.minebox: INFO
    io.minebox.nbd.NbdStatsReporter: INFO
    org.bitcoin.Secp256k1Context: ERROR
#    io.minebox.nbd.TransmissionPhase: INFO

#netty-spectific settings of minebd
minebd:
  nbdPort : 10809
  maxOpenFiles : 20
  parentDirs:
   - /mnt/lower1/data/
   - /mnt/lower2/data/
  reportedSize : 1TB
  maxUnflushed : 80MB
  minFreeSystemMem : 400MB
  encryptionKeyPath: /etc/minebox/minebox.key
  authFile: /etc/minebox/local-auth.key
  bucketSize : 40M
  httpMetadata: https://metadata.api.minebox.io/v1/metadata/
  ignoreMissingPaths: true
  siaDataDirectory: /mnt/lower1/sia
  siaClientUrl: "http://localhost:9980"

